rg_name        = "flask-vm-rg"
location       = "eastus"
vm_size        = "Standard_B1s"
admin_username = "azureuser"
admin_password = "YourPassword123!"
subscription_id = "your-azure-subscription-id"
